export const options = [
  {
    value: "chocolate",
    label: "м. Львів вул. Залізнична, буд. 65",
  },
  { value: "strawberry", label: "м. Львів вул. УПА, буд. 65" },
  { value: "vanilla", label: "м. Львів вул. Квітки, буд. 65" },
  { value: "vanjj", label: "м. Львів вул. Замарстинівська, буд. 65" },
  { value: "chocolaввte", label: "м. Львів вул. Залізнична, буд. 65" },
  { value: "strawввberry", label: "м. Львів вул. УПА, буд. 65" },
  { value: "vaniвваіваlla", label: "м. Львів вул. Квітки, буд. 65" },
  { value: "vanіваіваjj", label: "м. Львів вул. Замарстинівська, буд. 65" },
  { value: "strawberry", label: "м. Львів вул. УПА, буд. 65" },
  { value: "vanilla", label: "м. Львів вул. Квітки, буд. 65" },
  { value: "vanjj", label: "м. Львів вул. Замарстинівська, буд. 65" },
  { value: "chocolaввte", label: "м. Львів вул. Залізнична, буд. 65" },
  { value: "strawввberry", label: "м. Львів вул. УПА, буд. 65" },
  { value: "vaniвваіваlla", label: "м. Львів вул. Квітки, буд. 65" },
  { value: "vanіваіваjj", label: "м. Львів вул. Замарстинівська, буд. 65" },
];
